// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadiScanner.Infra;

#nullable disable

namespace PadiScanner.Migrations
{
    [DbContext(typeof(PadiDataContext))]
    [Migration("20221002070702_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PadiScanner.Data.PredictionHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("ClippedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatmapImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("OriginalImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverlayedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Probabilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploaderId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("PadiScanner.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "01GE24HFHHQZRRN024W32W8XF7",
                            FullName = "Fahmi Noor Fiqri",
                            LastLoginAt = new DateTime(2022, 10, 2, 14, 7, 1, 536, DateTimeKind.Local).AddTicks(11),
                            Password = "$2a$11$6Bih5edhY8tv5xkLxJyTbeC8bazNYYkCxFGljliYtV2pp.1nUNX9m",
                            Role = 0,
                            Username = "fahmi"
                        },
                        new
                        {
                            Id = "01GEBQMKK8SA2H2RSFXSCJFTMT",
                            FullName = "Hanif Hanan Al-Jufri",
                            LastLoginAt = new DateTime(2022, 10, 2, 14, 7, 1, 685, DateTimeKind.Local).AddTicks(9089),
                            Password = "$2a$11$tYymUy7M5iYwyuCCbkOibuxT8yAJDS/Ct5bVds0CwV2/bwlcvK6je",
                            Role = 1,
                            Username = "hanif"
                        },
                        new
                        {
                            Id = "01GEBQQ94E0Z8JBWGVJQNNH1N6",
                            FullName = "Abimanyu Okysaputra Rachman",
                            LastLoginAt = new DateTime(2022, 10, 2, 14, 7, 1, 838, DateTimeKind.Local).AddTicks(6598),
                            Password = "$2a$11$3nC40lWoH9DXeBXFMg0MRujojdAio1uMBKapNoUVofj3UEe.lkpoy",
                            Role = 1,
                            Username = "abimanyu"
                        },
                        new
                        {
                            Id = "01GE24MT8165ZNXACDZYC8GMEQ",
                            FullName = "Tamu",
                            LastLoginAt = new DateTime(2022, 10, 2, 14, 7, 1, 987, DateTimeKind.Local).AddTicks(1043),
                            Password = "$2a$11$DUhAeefkh9djTb9dSyqnhuxJ3gjHZ6/BkGEfOoTkSi5cAsDr1E3ku",
                            Role = 2,
                            Username = "tamu"
                        });
                });

            modelBuilder.Entity("PadiScanner.Data.PredictionHistory", b =>
                {
                    b.HasOne("PadiScanner.Data.User", "Uploader")
                        .WithMany("Predictions")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("PadiScanner.Data.User", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
